# Sp500 index daily

link: https://www.kaggle.com/datasets/andrewmvd/sp-500-stocks?select=sp500_index.csv

In [1]:
import pandas as pd
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor
import plotly.graph_objects as go

In [2]:
df = pd.read_csv("../data/01_raw/sp500_index.csv")
df["Date"] = pd.to_datetime(df["Date"], format="%Y-%m-%d")
df = df.set_index("Date").asfreq("D").ffill().reset_index()
df["item_id"] = "SP500"
df

           Date   S&P500 item_id
0    2014-12-22  2078.54   SP500
1    2014-12-23  2082.17   SP500
2    2014-12-24  2081.88   SP500
3    2014-12-25  2081.88   SP500
4    2014-12-26  2088.77   SP500
...         ...      ...     ...
3647 2024-12-16  6074.08   SP500
3648 2024-12-17  6050.61   SP500
3649 2024-12-18  5872.16   SP500
3650 2024-12-19  5867.08   SP500
3651 2024-12-20  5930.85   SP500

[3652 rows x 3 columns]

In [3]:
PREDICTION_LENGTH=30
TARGET="S&P500"

In [4]:
train_data = TimeSeriesDataFrame.from_data_frame(
    df, id_column="item_id", timestamp_column="Date"
)

train_split, test_split = train_data.train_test_split(
    prediction_length=PREDICTION_LENGTH
)

predictor = TimeSeriesPredictor(
    prediction_length=PREDICTION_LENGTH,
    quantile_levels=[0.025, 0.05, 0.5, 0.95 ,0.975],
    target=TARGET,
    eval_metric="WAPE",
)

predictor.fit(
    train_split,
    hyperparameters={
        "RecursiveTabular": {
            "tabular_hyperparameters": {"GBM": {}, "XGB": {}, "CAT": {}}
        },
        "Naive": {},
        "SeasonalNaive": {},
        "PatchTST": {},
        "ETS": {},
        "ADIDA": {},
        "DLinear": {},
        "Toto": {},
        "ARIMA": {},
        "Theta": {},
        "DeepAR": {},
        "NPTS": {},
        "TemporalFusionTransformer": {},
        "Chronos2": {},
        "SimpleFeedForward": {},
        "TiDE":{},
        "WaveNet": {},
    },
)

Beginning AutoGluon training...
AutoGluon will save models to '/home/cezartdev/Documents/cezartdev/personal/walmart_sales_benchmark_mlops/notebooks/AutogluonModels/ag-20260518_045449'
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Thu Mar  5 00:10:35 UTC 2026
CPU Count:          12
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 11.62/11.62 GB
Total GPU Memory:   Free: 11.62 GB, Allocated: 0.00 GB, Total: 11.62 GB
GPU Count:          1
Memory Avail:       18.32 GB / 31.15 GB (58.8%)
Disk Space Avail:   110.98 GB / 230.30 GB (48.2%)
===================================================

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WAPE,
 'hyperparameters': {'ADIDA': {},
                     'ARIMA': {},
                     'Chronos2': {},
                     'DLinear': {},
                     'DeepAR': {},
                     'ETS': {},
                     'NPTS': {},
                     'Naive': {},
                     'PatchTST': {},
                     'RecursiveTabular': {'tabular_hyperparameters': {'CAT': {},
                                                                      'GBM': {},
                                                                      'XGB': {}}},
                     'SeasonalNaive': {},
                     'SimpleFeedForward': {},
                     'TemporalFusionTransformer': {},
                     'Theta': {},
                     'TiDE': {},
                     'Toto': {},
                     'WaveNet': {}},
 'known_covariates_names': [],
 'num_val_windows': 1,
 'prediction_length': 30,
 'quantile_levels': [0.025, 0.05, 0.5, 0.95, 0.975],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'S&P500',
 'verbosity': 2}

Inferred time series frequency: 'D'
Provided train_data has 3622 rows, 1 time series. Median time series length is 3622 (min=3622, max=3622).

Provided data contains following columns:
	target: 'S&P500'

AutoGluon will gauge predictive performance using evaluation metric: 'WAPE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2026-05-18 00:54:50
Models that will be trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'ETS', 'NPTS', 'Theta', 'Chronos2', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'TiDE', 'WaveNet', 'ADIDA', 'DLinear', 'ARIMA', 'SimpleFeedForward', 'Toto']
Training timeseries model Naive.
	-0.0137       = Validation score (-WAPE)
	0.01    s     = Training runtime
	0.96    s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive.
	-0.0141       = Validation score (-WAPE)
	0.01    s     = Training runtime
	0.89    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular.
RecursiveTabular/W0 ignores following hyperparameters: ['tabular_hyperparameters']. See the documentation for RecursiveTabular/W0 for the list of supported hyperparameters.
	-0.0132       = Validation score (-WAPE)
	0.42    s     = Training runtime
	0.06    s     = Validation (prediction) runtime
Training timeseries model ETS.
	-0.0137       = Validation score (-WAPE)
	0.01    s     = Training runtime
	1.73    s     = Validation (prediction) runtime
Training timeseries model NPTS.
	-0.3013       = Validation score (-WAPE)
	0.01    s     = Training runtime
	1.01    s     = Validation (prediction) runtime
Training timeseries model Theta.
	-0.0141       = Validation score (-WAPE)
	0.01    s     = Training runtime
	1.23    s     = Validation (prediction) runtime
Training timeseries model Chronos2.
	-0.0121       = Validation score (-WAPE)
	2.60    s     = Training runtime
	0.28    s     = Validation (prediction) runtime
Training timeseries model TemporalFusionTransformer.
	-0.0115       = Validation score (-WAPE)
	32.63   s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model DeepAR.
	-0.0129       = Validation score (-WAPE)
	49.99   s     = Training runtime
	0.08    s     = Validation (prediction) runtime
Training timeseries model PatchTST.
	-0.0112       = Validation score (-WAPE)
	21.52   s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model TiDE.
	-0.0122       = Validation score (-WAPE)
	58.86   s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model WaveNet.
	-0.0168       = Validation score (-WAPE)
	23.74   s     = Training runtime
	0.08    s     = Validation (prediction) runtime
Training timeseries model ADIDA.
	-0.0137       = Validation score (-WAPE)
	0.00    s     = Training runtime
	1.89    s     = Validation (prediction) runtime
Training timeseries model DLinear.
	-0.0114       = Validation score (-WAPE)
	21.20   s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model ARIMA.
	-0.0137       = Validation score (-WAPE)
	0.01    s     = Training runtime
	1.07    s     = Validation (prediction) runtime
Training timeseries model SimpleFeedForward.
	-0.0113       = Validation score (-WAPE)
	11.75   s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model Toto.
	-0.0137       = Validation score (-WAPE)
	1.58    s     = Training runtime
	0.99    s     = Validation (prediction) runtime
Fitting 1 ensemble(s), in 1 layers.
Training ensemble model WeightedEnsemble.
	Ensemble weights: {'DLinear': 0.02, 'DeepAR': 0.02, 'PatchTST': 0.11, 'SimpleFeedForward': 0.56, 'TemporalFusionTransformer': 0.3}
	-0.0105       = Validation score (-WAPE)
	0.21    s     = Training runtime
	0.11    s     = Validation (prediction) runtime
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'ETS', 'NPTS', 'Theta', 'Chronos2', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'TiDE', 'WaveNet', 'ADIDA', 'DLinear', 'ARIMA', 'SimpleFeedForward', 'Toto', 'WeightedEnsemble']
Total runtime: 235.42 s
Best model: WeightedEnsemble
Best model score: -0.0105

In [5]:
leaderboard = predictor.leaderboard(train_split)

Additional data provided, testing on additional data. Resulting leaderboard will be sorted according to test score (`score_test`).

In [6]:
leaderboard

,model,score_test,score_val,pred_time_test,pred_time_val,fit_time_marginal,fit_order
0,WeightedEnsemble,-0.010507,-0.010508,0.153851,0.108024,0.205914,18
1,PatchTST,-0.011177,-0.011177,0.016509,0.006436,21.515582,10
2,SimpleFeedForward,-0.011331,-0.011331,0.012872,0.005689,11.746289,16
3,DLinear,-0.011405,-0.011405,0.010011,0.006800,21.198540,14
4,TemporalFusionTransformer,-0.011550,-0.011550,0.036938,0.010091,32.625190,8
5,Chronos2,-0.012132,-0.012132,0.903795,0.276452,2.600151,7
6,TiDE,-0.012232,-0.012232,0.019816,0.007907,58.862487,11
7,RecursiveTabular,-0.013232,-0.013232,0.064847,0.061068,0.417245,3
8,DeepAR,-0.013290,-0.012896,0.076279,0.077463,49.993927,9
9,Toto,-0.013646,-0.013747,2.527668,0.989011,1.575875,17
10,Naive,-0.013690,-0.013690,0.013486,0.956490,0.005699,1
11,ETS,-0.013690,-0.013690,0.587584,1.725638,0.005388,4
12,ADIDA,-0.013690,-0.013690,0.014333,1.885147,0.004985,13
13,ARIMA,-0.013691,-0.013691,1.062526,1.070930,0.005207,15
14,Theta,-0.014078,-0.014078,1.221632,1.231790,0.005510,6
15,SeasonalNaive,-0.014145,-0.014145,0.789271,0.891014,0.005164,2
16,WaveNet,-0.016126,-0.016757,0.049159,0.075686,23.738254,12
17,NPTS,-0.301300,-0.301300,0.990722,1.010524,0.005351,5

In [7]:
predictions = predictor.predict(train_split, model="WeightedEnsemble")

In [8]:
selected_item = "SP500"

real_data = test_split.loc[selected_item]
predictions_store = predictions.loc[selected_item]

In [9]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=real_data.index,
        y=real_data[TARGET],
        name="Actual S&P500 Price",
        mode="lines",
        line=dict(color="#1f77b4", width=2),
    )
)

fig.add_trace(
    go.Scatter(
        x=predictions_store.index,
        y=predictions_store["mean"],
        name="Forecast (Mean)",
        mode="lines",
        line=dict(color="#ff7f0e", width=2, dash="dash"),
    )
)

fig.add_trace(
    go.Scatter(
        x=predictions_store.index,
        y=predictions_store["0.975"],
        name="Upper Bound (p97.5)",
        mode="lines",
        line=dict(width=0),
        showlegend=False,
    )
)

fig.add_trace(
    go.Scatter(
        x=predictions_store.index,
        y=predictions_store["0.025"],
        name="95% Confidence Interval (p2.5 - p97.5)",
        mode="lines",
        fill="tonexty",
        fillcolor="rgba(255, 127, 14, 0.15)",
        line=dict(width=0),
    )
)

fig.add_trace(
    go.Scatter(
        x=predictions_store.index,
        y=predictions_store["0.95"],
        name="Upper Bound (p95)",
        mode="lines",
        line=dict(width=0),
        showlegend=False,
    )
)

fig.add_trace(
    go.Scatter(
        x=predictions_store.index,
        y=predictions_store["0.05"],
        name="90% Confidence Interval (p5 - p95)",
        mode="lines",
        fill="tonexty",
        fillcolor="rgba(200, 100, 14, 0.15)",
        line=dict(width=0),
    )
)

fig.update_layout(
    title=f"Backtesting (Actual vs Forecast) - {selected_item}",
    xaxis_title="Date",
    yaxis_title="S&P 500 Index Price ($)",
    template="plotly_white",
    hovermode="x unified",
)
fig.show()

## Weekly Analysis & Forecasting

In this section, we group the daily data by week, using the value from the start of the week (Monday) and omitting the other days, in order to perform a weekly forecast analysis.

In [ ]:
df_weekly = df.set_index("Date").resample("W-MON").first().reset_index()

df_weekly["item_id"] = "SP500_weekly"
PREDICTION_LENGTH_WEEKLY = 13  
TARGET_WEEKLY = "S&P500"

df_weekly.head(10)

        Date   S&P500       item_id
0 2014-12-22  2078.54  SP500_weekly
1 2014-12-29  2082.17  SP500_weekly
2 2015-01-05  2080.35  SP500_weekly
3 2015-01-12  2002.61  SP500_weekly
4 2015-01-19  2023.03  SP500_weekly
5 2015-01-26  2022.55  SP500_weekly
6 2015-02-02  2029.55  SP500_weekly
7 2015-02-09  2050.03  SP500_weekly
8 2015-02-16  2068.59  SP500_weekly
9 2015-02-23  2100.34  SP500_weekly

In [ ]:
train_data_weekly = TimeSeriesDataFrame.from_data_frame(
    df_weekly, id_column="item_id", timestamp_column="Date"
)

train_split_weekly, test_split_weekly = train_data_weekly.train_test_split(
    prediction_length=PREDICTION_LENGTH_WEEKLY
)


predictor_weekly = TimeSeriesPredictor(
    prediction_length=PREDICTION_LENGTH_WEEKLY,
    quantile_levels=[0.025, 0.05, 0.5, 0.95, 0.975],
    target=TARGET_WEEKLY,
    eval_metric="WAPE",
)

predictor_weekly.fit(
    train_split_weekly,
    hyperparameters={
        "RecursiveTabular": {
            "tabular_hyperparameters": {"GBM": {}, "XGB": {}, "CAT": {}}
        },
        "Naive": {},
        "SeasonalNaive": {},
        "PatchTST": {},
        "ETS": {},
        "ADIDA": {},
        "DLinear": {},
        "Toto": {},
        "ARIMA": {},
        "Theta": {},
        "DeepAR": {},
        "NPTS": {},
        "TemporalFusionTransformer": {},
        "Chronos2": {},
        "SimpleFeedForward": {},
        "TiDE": {},
        "WaveNet": {},
    },
)

No path specified. Models will be saved in: "AutogluonModels/ag-20260518_045855"
Beginning AutoGluon training...
AutoGluon will save models to '/home/cezartdev/Documents/cezartdev/personal/walmart_sales_benchmark_mlops/notebooks/AutogluonModels/ag-20260518_045855'
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Thu Mar  5 00:10:35 UTC 2026
CPU Count:          12
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 10.59/11.62 GB
Total GPU Memory:   Free: 10.59 GB, Allocated: 1.03 GB, Total: 11.62 GB
GPU Count:          1
Memory Avail:       15.05 GB / 31.15 GB (48.3%)
Disk Space Avail:   110.98 GB / 230.30 GB (48.2%)
===================================================

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WAPE,
 'hyperparameters': {'ADIDA': {},
                     'ARIMA': {},
                     'Chronos2': {},
                     'DLinear': {},
                     'DeepAR': {},
                     'ETS': {},
                     'NPTS': {},
                     'Naive': {},
                     'PatchTST': {},
                     'RecursiveTabular': {'tabular_hyperparameters': {'CAT': {},
                                                                      'GBM': {},
                                                                      'XGB': {}}},
                     'SeasonalNaive': {},
                     'SimpleFeedForward': {},
                     'TemporalFusionTransformer': {},
                     'Theta': {},
                     'TiDE': {},
                     'Toto': {},
                     'WaveNet': {}},
 'known_covariates_names': [],
 'num_val_windows': 1,
 'prediction_length': 13,
 'quantile_levels': [0.025, 0.05, 0.5, 0.95, 0.975],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'S&P500',
 'verbosity': 2}

Inferred time series frequency: 'W-MON'
Provided train_data has 510 rows, 1 time series. Median time series length is 510 (min=510, max=510).

Provided data contains following columns:
	target: 'S&P500'

AutoGluon will gauge predictive performance using evaluation metric: 'WAPE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2026-05-18 00:58:55
Models that will be trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'ETS', 'NPTS', 'Theta', 'Chronos2', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'TiDE', 'WaveNet', 'ADIDA', 'DLinear', 'ARIMA', 'SimpleFeedForward', 'Toto']
Training timeseries model Naive.
	-0.0164       = Validation score (-WAPE)
	0.00    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive.
	-0.0164       = Validation score (-WAPE)
	0.00    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular.
RecursiveTabular/W0 ignores following hyperparameters: ['tabular_hyperparameters']. See the documentation for RecursiveTabular/W0 for the list of supported hyperparameters.
	-0.0162       = Validation score (-WAPE)
	0.29    s     = Training runtime
	0.04    s     = Validation (prediction) runtime
Training timeseries model ETS.
	-0.0149       = Validation score (-WAPE)
	0.00    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model NPTS.
	-0.3635       = Validation score (-WAPE)
	0.00    s     = Training runtime
	0.03    s     = Validation (prediction) runtime
Training timeseries model Theta.
	-0.0162       = Validation score (-WAPE)
	0.00    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model Chronos2.
	-0.0167       = Validation score (-WAPE)
	0.88    s     = Training runtime
	0.02    s     = Validation (prediction) runtime
Training timeseries model TemporalFusionTransformer.
	-0.0181       = Validation score (-WAPE)
	28.68   s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model DeepAR.
	-0.0202       = Validation score (-WAPE)
	26.75   s     = Training runtime
	0.03    s     = Validation (prediction) runtime
Training timeseries model PatchTST.
	-0.0159       = Validation score (-WAPE)
	10.54   s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model TiDE.
	-0.0156       = Validation score (-WAPE)
	34.85   s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model WaveNet.
	-0.0152       = Validation score (-WAPE)
	10.97   s     = Training runtime
	0.03    s     = Validation (prediction) runtime
Training timeseries model ADIDA.
	-0.0342       = Validation score (-WAPE)
	0.00    s     = Training runtime
	0.40    s     = Validation (prediction) runtime
Training timeseries model DLinear.
	-0.0132       = Validation score (-WAPE)
	9.74    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model ARIMA.
	-0.0161       = Validation score (-WAPE)
	0.00    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model SimpleFeedForward.
	-0.0141       = Validation score (-WAPE)
	16.59   s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model Toto.
	-0.0201       = Validation score (-WAPE)
	1.57    s     = Training runtime
	0.20    s     = Validation (prediction) runtime
Fitting 1 ensemble(s), in 1 layers.
Training ensemble model WeightedEnsemble.
	Ensemble weights: {'DLinear': 0.48, 'PatchTST': 0.22, 'SimpleFeedForward': 0.13, 'WaveNet': 0.17}
	-0.0114       = Validation score (-WAPE)
	0.20    s     = Training runtime
	0.04    s     = Validation (prediction) runtime
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'ETS', 'NPTS', 'Theta', 'Chronos2', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'TiDE', 'WaveNet', 'ADIDA', 'DLinear', 'ARIMA', 'SimpleFeedForward', 'Toto', 'WeightedEnsemble']
Total runtime: 142.18 s
Best model: WeightedEnsemble
Best model score: -0.0114

In [12]:
leaderboard_weekly = predictor_weekly.leaderboard(train_split_weekly)
leaderboard_weekly

Additional data provided, testing on additional data. Resulting leaderboard will be sorted according to test score (`score_test`).

,model,score_test,score_val,pred_time_test,pred_time_val,fit_time_marginal,fit_order
0,WeightedEnsemble,-0.011647,-0.011371,0.064861,0.043213,0.201319,18
1,DLinear,-0.013158,-0.013158,0.008940,0.005419,9.735653,14
2,SimpleFeedForward,-0.014130,-0.014130,0.010805,0.005115,16.588501,16
3,ETS,-0.014891,-0.014891,0.013550,0.013367,0.004457,4
4,TiDE,-0.015611,-0.015611,0.018499,0.007057,34.854047,11
5,WaveNet,-0.015678,-0.015186,0.028710,0.025471,10.966705,12
6,PatchTST,-0.015894,-0.015894,0.015362,0.005890,10.536118,10
7,ARIMA,-0.016109,-0.016109,0.013515,0.013267,0.004422,15
8,RecursiveTabular,-0.016171,-0.016171,0.039703,0.036394,0.286592,3
9,Theta,-0.016173,-0.016173,0.326066,0.013001,0.004322,6
10,SeasonalNaive,-0.016379,-0.016379,0.013443,0.013429,0.004856,2
11,Naive,-0.016379,-0.016379,0.013481,0.013697,0.004213,1
12,Chronos2,-0.016651,-0.016651,0.907153,0.018582,0.884952,7
13,TemporalFusionTransformer,-0.018092,-0.018092,0.036188,0.008080,28.682990,8
14,DeepAR,-0.018535,-0.020171,0.037559,0.031041,26.747434,9
15,Toto,-0.019295,-0.020080,1.762029,0.198465,1.568334,17
16,ADIDA,-0.034182,-0.034182,0.013466,0.395985,0.004452,13
17,NPTS,-0.363539,-0.363539,0.033457,0.033387,0.003979,5

In [13]:
predictions_weekly = predictor_weekly.predict(train_split_weekly, model="WeightedEnsemble")

In [14]:
selected_item_weekly = "SP500_weekly"

real_data_weekly = test_split_weekly.loc[selected_item_weekly]
predictions_weekly_store = predictions_weekly.loc[selected_item_weekly]

fig_weekly = go.Figure()

fig_weekly.add_trace(
    go.Scatter(
        x=real_data_weekly.index,
        y=real_data_weekly[TARGET_WEEKLY],
        name="Actual S&P500 Price (Weekly)",
        mode="lines",
        line=dict(color="#1f77b4", width=2),
    )
)

fig_weekly.add_trace(
    go.Scatter(
        x=predictions_weekly_store.index,
        y=predictions_weekly_store["mean"],
        name="Forecast (Mean)",
        mode="lines",
        line=dict(color="#ff7f0e", width=2, dash="dash"),
    )
)

fig_weekly.add_trace(
    go.Scatter(
        x=predictions_weekly_store.index,
        y=predictions_weekly_store["0.975"],
        name="Upper Bound (p97.5)",
        mode="lines",
        line=dict(width=0),
        showlegend=False,
    )
)

fig_weekly.add_trace(
    go.Scatter(
        x=predictions_weekly_store.index,
        y=predictions_weekly_store["0.025"],
        name="95% Confidence Interval (p2.5 - p97.5)",
        mode="lines",
        fill="tonexty",
        fillcolor="rgba(255, 127, 14, 0.15)",
        line=dict(width=0),
    )
)

fig_weekly.add_trace(
    go.Scatter(
        x=predictions_weekly_store.index,
        y=predictions_weekly_store["0.95"],
        name="Upper Bound (p95)",
        mode="lines",
        line=dict(width=0),
        showlegend=False,
    )
)

fig_weekly.add_trace(
    go.Scatter(
        x=predictions_weekly_store.index,
        y=predictions_weekly_store["0.05"],
        name="90% Confidence Interval (p5 - p95)",
        mode="lines",
        fill="tonexty",
        fillcolor="rgba(200, 100, 14, 0.15)",
        line=dict(width=0),
    )
)

fig_weekly.update_layout(
    title=f"Backtesting Semanal (Actual vs Forecast) - {selected_item_weekly}",
    xaxis_title="Date",
    yaxis_title="S&P 500 Index Price ($)",
    template="plotly_white",
    hovermode="x unified",
)
fig_weekly.show()

## Monthly Analysis & Forecasting

In this section, we resample the daily S&P 500 index data to a monthly frequency. We select the first available trading day's value of each month and skip the remaining days. We then train an AutoGluon TimeSeriesPredictor to forecast the index price at a monthly resolution.

In [15]:
df_monthly = df.set_index("Date").resample("MS").first().reset_index()

df_monthly["item_id"] = "SP500_monthly"
PREDICTION_LENGTH_MONTHLY = 12  
TARGET_MONTHLY = "S&P500"

df_monthly.head(12)

         Date   S&P500        item_id
0  2014-12-01  2078.54  SP500_monthly
1  2015-01-01  2058.90  SP500_monthly
2  2015-02-01  1994.99  SP500_monthly
3  2015-03-01  2104.50  SP500_monthly
4  2015-04-01  2059.69  SP500_monthly
5  2015-05-01  2108.29  SP500_monthly
6  2015-06-01  2111.73  SP500_monthly
7  2015-07-01  2077.42  SP500_monthly
8  2015-08-01  2103.84  SP500_monthly
9  2015-09-01  1913.85  SP500_monthly
10 2015-10-01  1923.82  SP500_monthly
11 2015-11-01  2079.36  SP500_monthly

In [16]:
train_data_monthly = TimeSeriesDataFrame.from_data_frame(
    df_monthly, id_column="item_id", timestamp_column="Date"
)

train_split_monthly, test_split_monthly = train_data_monthly.train_test_split(
    prediction_length=PREDICTION_LENGTH_MONTHLY
)

predictor_monthly = TimeSeriesPredictor(
    prediction_length=PREDICTION_LENGTH_MONTHLY,
    quantile_levels=[0.025, 0.05, 0.5, 0.95, 0.975],
    target=TARGET_MONTHLY,
    eval_metric="WAPE",
)

predictor_monthly.fit(
    train_split_monthly,
    hyperparameters={
        "RecursiveTabular": {
            "tabular_hyperparameters": {"GBM": {}, "XGB": {}, "CAT": {}}
        },
        "Naive": {},
        "SeasonalNaive": {},
        "PatchTST": {},
        "ETS": {},
        "ADIDA": {},
        "DLinear": {},
        "Toto": {},
        "ARIMA": {},
        "Theta": {},
        "DeepAR": {},
        "NPTS": {},
        "TemporalFusionTransformer": {},
        "Chronos2": {},
        "SimpleFeedForward": {},
        "TiDE": {},
        "WaveNet": {},
    },
)

No path specified. Models will be saved in: "AutogluonModels/ag-20260518_050120"
Beginning AutoGluon training...
AutoGluon will save models to '/home/cezartdev/Documents/cezartdev/personal/walmart_sales_benchmark_mlops/notebooks/AutogluonModels/ag-20260518_050120'
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Thu Mar  5 00:10:35 UTC 2026
CPU Count:          12
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 11.61/11.62 GB
Total GPU Memory:   Free: 11.61 GB, Allocated: 0.01 GB, Total: 11.62 GB
GPU Count:          1
Memory Avail:       14.26 GB / 31.15 GB (45.8%)
Disk Space Avail:   110.98 GB / 230.30 GB (48.2%)
===================================================

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WAPE,
 'hyperparameters': {'ADIDA': {},
                     'ARIMA': {},
                     'Chronos2': {},
                     'DLinear': {},
                     'DeepAR': {},
                     'ETS': {},
                     'NPTS': {},
                     'Naive': {},
                     'PatchTST': {},
                     'RecursiveTabular': {'tabular_hyperparameters': {'CAT': {},
                                                                      'GBM': {},
                                                                      'XGB': {}}},
                     'SeasonalNaive': {},
                     'SimpleFeedForward': {},
                     'TemporalFusionTransformer': {},
                     'Theta': {},
                     'TiDE': {},
                     'Toto': {},
                     'WaveNet': {}},
 'known_covariates_names': [],
 'num_val_windows': 1,
 'prediction_length': 12,
 'quantile_levels': [0.025, 0.05, 0.5, 0.95, 0.975],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'S&P500',
 'verbosity': 2}

Inferred time series frequency: 'MS'
Provided train_data has 109 rows, 1 time series. Median time series length is 109 (min=109, max=109).

Provided data contains following columns:
	target: 'S&P500'

AutoGluon will gauge predictive performance using evaluation metric: 'WAPE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2026-05-18 01:01:20
Models that will be trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'ETS', 'NPTS', 'Theta', 'Chronos2', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'TiDE', 'WaveNet', 'ADIDA', 'DLinear', 'ARIMA', 'SimpleFeedForward', 'Toto']
Training timeseries model Naive.
	-0.0563       = Validation score (-WAPE)
	0.01    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive.
	-0.1084       = Validation score (-WAPE)
	0.01    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular.
RecursiveTabular/W0 ignores following hyperparameters: ['tabular_hyperparameters']. See the documentation for RecursiveTabular/W0 for the list of supported hyperparameters.
	-0.0770       = Validation score (-WAPE)
	0.21    s     = Training runtime
	0.03    s     = Validation (prediction) runtime
Training timeseries model ETS.
	-0.0644       = Validation score (-WAPE)
	0.01    s     = Training runtime
	0.04    s     = Validation (prediction) runtime
Training timeseries model NPTS.
	-0.3116       = Validation score (-WAPE)
	0.00    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model Theta.
	-0.0475       = Validation score (-WAPE)
	0.00    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model Chronos2.
	-0.0692       = Validation score (-WAPE)
	0.92    s     = Training runtime
	0.02    s     = Validation (prediction) runtime
Training timeseries model TemporalFusionTransformer.
	-0.1575       = Validation score (-WAPE)
	15.29   s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model DeepAR.
	-0.0533       = Validation score (-WAPE)
	7.99    s     = Training runtime
	0.03    s     = Validation (prediction) runtime
Training timeseries model PatchTST.
	-0.0865       = Validation score (-WAPE)
	12.34   s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model TiDE.
	-0.1821       = Validation score (-WAPE)
	22.18   s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model WaveNet.
	-0.1126       = Validation score (-WAPE)
	10.75   s     = Training runtime
	0.02    s     = Validation (prediction) runtime
Training timeseries model ADIDA.
	-0.0741       = Validation score (-WAPE)
	0.00    s     = Training runtime
	0.39    s     = Validation (prediction) runtime
Training timeseries model DLinear.
	-0.1624       = Validation score (-WAPE)
	11.40   s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model ARIMA.
	-0.0639       = Validation score (-WAPE)
	0.00    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model SimpleFeedForward.
	-0.0715       = Validation score (-WAPE)
	7.78    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model Toto.
	-0.0672       = Validation score (-WAPE)
	1.58    s     = Training runtime
	0.12    s     = Validation (prediction) runtime
Fitting 1 ensemble(s), in 1 layers.
Training ensemble model WeightedEnsemble.
	Ensemble weights: {'ADIDA': 0.03, 'Chronos2': 0.01, 'SimpleFeedForward': 0.25, 'Theta': 0.7}
	-0.0322       = Validation score (-WAPE)
	0.21    s     = Training runtime
	0.42    s     = Validation (prediction) runtime
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'ETS', 'NPTS', 'Theta', 'Chronos2', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'TiDE', 'WaveNet', 'ADIDA', 'DLinear', 'ARIMA', 'SimpleFeedForward', 'Toto', 'WeightedEnsemble']
Total runtime: 91.65 s
Best model: WeightedEnsemble
Best model score: -0.0322

In [17]:
leaderboard_monthly = predictor_monthly.leaderboard(train_split_monthly)
leaderboard_monthly

Additional data provided, testing on additional data. Resulting leaderboard will be sorted according to test score (`score_test`).

,model,score_test,score_val,pred_time_test,pred_time_val,fit_time_marginal,fit_order
0,WeightedEnsemble,-0.032218,-0.032218,1.226604,0.422296,0.208043,18
1,Theta,-0.047517,-0.047517,0.296205,0.013069,0.004675,6
2,Naive,-0.056340,-0.056340,0.012984,0.013689,0.005125,1
3,DeepAR,-0.060062,-0.053264,0.035581,0.028899,7.991600,9
4,ARIMA,-0.063919,-0.063919,0.013325,0.013285,0.004414,15
5,ETS,-0.064382,-0.064382,0.043576,0.043419,0.005057,4
6,Toto,-0.067146,-0.067200,1.724977,0.120504,1.584159,17
7,Chronos2,-0.069169,-0.069169,0.905747,0.016184,0.918376,7
8,SimpleFeedForward,-0.071509,-0.071509,0.010393,0.005681,7.780708,16
9,ADIDA,-0.074081,-0.074081,0.013161,0.385605,0.004191,13
10,RecursiveTabular,-0.076962,-0.076962,0.034615,0.030118,0.211832,3
11,PatchTST,-0.086470,-0.086470,0.015522,0.005714,12.343790,10
12,SeasonalNaive,-0.108386,-0.108386,0.013444,0.014035,0.005603,2
13,WaveNet,-0.117529,-0.112611,0.027599,0.017084,10.752010,12
14,TemporalFusionTransformer,-0.157527,-0.157527,0.035310,0.007709,15.290508,8
15,DLinear,-0.162368,-0.162368,0.010304,0.006198,11.396339,14
16,TiDE,-0.182074,-0.182074,0.017987,0.009655,22.175284,11
17,NPTS,-0.311569,-0.311569,0.013019,0.013001,0.004246,5

In [ ]:
predictions_monthly = predictor_monthly.predict(train_split_monthly, model="WeightedEnsemble")

In [23]:
selected_item_monthly = "SP500_monthly"

real_data_monthly = test_split_monthly.loc[selected_item_monthly]
predictions_monthly_store = predictions_monthly.loc[selected_item_monthly]

fig_monthly = go.Figure()

fig_monthly.add_trace(
    go.Scatter(
        x=real_data_monthly.index,
        y=real_data_monthly[TARGET_MONTHLY],
        name="Actual S&P500 Price (Monthly)",
        mode="lines",
        line=dict(color="#1f77b4", width=2),
    )
)


fig_monthly.add_trace(
    go.Scatter(
        x=predictions_monthly_store.index,
        y=predictions_monthly_store["mean"],
        name="Forecast (Mean)",
        mode="lines",
        line=dict(color="#ff7f0e", width=2, dash="dash"),
    )
)


fig_monthly.add_trace(
    go.Scatter(
        x=predictions_monthly_store.index,
        y=predictions_monthly_store["0.975"],
        name="Upper Bound (p97.5)",
        mode="lines",
        line=dict(width=0),
        showlegend=False,
    )
)

fig_monthly.add_trace(
    go.Scatter(
        x=predictions_monthly_store.index,
        y=predictions_monthly_store["0.025"],
        name="95% Confidence Interval (p2.5 - p97.5)",
        mode="lines",
        fill="tonexty",
        fillcolor="rgba(255, 127, 14, 0.15)",
        line=dict(width=0),
    )
)

fig_monthly.add_trace(
    go.Scatter(
        x=predictions_monthly_store.index,
        y=predictions_monthly_store["0.95"],
        name="Upper Bound (p95)",
        mode="lines",
        line=dict(width=0),
        showlegend=False,
    )
)

fig_monthly.add_trace(
    go.Scatter(
        x=predictions_monthly_store.index,
        y=predictions_monthly_store["0.05"],
        name="90% Confidence Interval (p5 - p95)",
        mode="lines",
        fill="tonexty",
        fillcolor="rgba(200, 100, 14, 0.15)",
        line=dict(width=0),
    )
)

fig_monthly.update_layout(
    title=f"Monthly Backtesting (Actual vs Forecast) - {selected_item_monthly}",
    xaxis_title="Date",
    yaxis_title="S&P 500 Index Price ($)",
    template="plotly_white",
    hovermode="x unified",
)
fig_monthly.show()